MaquetacionHTML/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaquetacionHTML.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/

        public ActionResult Index()
        {
            return View();
        }
		  [HttpGet]
		  public ActionResult OTLista()
		  {
			  return PartialView();
		  }
		  [HttpGet]
		  public ActionResult FakeDescarga()
		  {
			  System.Threading.Thread.Sleep(5000);
			  return PartialView();
		  }
		  [HttpGet]
		  public ActionResult MisOrdenes()
		  {
			  return PartialView();
		  }
		  [HttpGet]
		  public ActionResult IniciarOrden()
		  {
			  return PartialView();
		  }
		  [HttpGet]
		  public ActionResult Modal()
		  {
			  return PartialView();
		  }
					  		  
    }
}

MaquetacionHTML/Views/Index/FakeDescarga.cshtml
Ordenes de trabajo sincronizadas

MaquetacionHTML/Views/Index/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
<p>Date: <input type="text" id="datepicker"></p>


<span class="label label-default">Default</span>
<span class="label label-primary">Primary</span>
<span class="label label-success">Success</span>
<span class="label label-info">Info</span>
<span class="label label-warning">Warning</span>
<span class="label label-danger">Danger</span>


<i class="fa fa-window-close fa-4x" aria-hidden="true"></i>*@
<style>  
    .lblIcons 
    {
        color:#286090 ;
    }
    .frmLoggin 
    {
        color:#fff;
    }
    .btn-primary {
        background-image: linear-gradient(to bottom, #286090 0%, #286090 100%);
    }
    .lblText 
    {
        color:#fff;
    }
    .lblTxtImg 
    {
        margin-left:10px !important;
    }
</style>

<div id="dvAllContenido" class="container">
    <div class="col-md-12 col-sm-12">        
        <form style="margin-top:10%;" class="frmLoggin">
            <div class="form-group">
                <label for="txtUser" class="lblIcons">
                    <i class="fa fa-user-circle fa-2x"></i>
                </label>
                <label class="lblText lblTxtImg">Usuario</label>
                <input type="email" class="form-control" id="txtUser" placeholder="Usuario">
            </div>
            <div class="form-group">
                <label for="txtClave" class="lblIcons">
                    <i class="fa fa-key fa-2x"></i>
                </label>
                <label class="lblText lblTxtImg">Clave</label>
                <input type="password" class="form-control" id="txtClave" placeholder="Clave">
            </div>            
            <span id="btnLoggin" type="submit" class="btn btn-primary" data-url="@Url.Action("OTLista", "Index")">
                <i class="fa fa-sign-in fa-1x"></i>
                Entrar
            </span>
        </form>
    </div>
</div>

MaquetacionHTML/Views/Index/IniciarOrden.cshtml
@Html.Partial("_Back")
<br />
<table class="table table-condensed table-bordered">
    <thead class="grid-Head navbar-default">
        <tr>           
            <th>
                <div><label for="Actividad">Actividad</label></div>
            </th>          
            <th>
                <div><label >Cantidad</label></div>
            </th>
            <th>
                <div><label>Cantidad Ejecutada</label></div>
            </th>
            <th>
                <div><label>Comentarios</label></div>
            </th>
        </tr>
    </thead>
    <tbody id="tablaOrdenesTrabajovwAdministrador" style="font-size:85%">
        <tr class="ui-rw-cat" data-property="IdOrdenTrabajo" data-property-value="80">
            <td >1.02 0 DUCTO GALVANIZADO </td>           
            <td>2 Mts</td>
            <td><input type="number" class="form-control" /></td>
            <td><input type="text" class="form-control" /></td>
        </tr>
        <tr class="ui-rw-cat" data-property="IdOrdenTrabajo" data-property-value="80">
            <td>1.04 0 GABINETES Y REGISTROS</td>            
            <td>8 Mts</td>
            <td><input type="number" class="form-control" /></td>
            <td><input type="text" class="form-control" /></td>
        </tr>
        <tr class="ui-rw-cat" data-property="IdOrdenTrabajo" data-property-value="80">
            <td>1.20 ZANJA </td>            
            <td>0.20 Mts</td>
            <td><input type="number" class="form-control" /></td>
            <td><input type="text" class="form-control" /></td>
        </tr>
        <tr class="ui-rw-cat" data-property="IdOrdenTrabajo" data-property-value="80">
            <td>3.0 COLOCACION DE CABLEADO </td>            
            <td>5 Mts</td>
            <td><input type="number" class="form-control" /></td>
            <td><input type="text" class="form-control" /></td>
        </tr>
        <tr class="ui-rw-cat" data-property="IdOrdenTrabajo" data-property-value="80">
            <td>3.02 COLOCACION DE JACKS </td>
            <td>100 PZAS</td>
            <td><input type="number" class="form-control" /></td>
            <td><input type="text" class="form-control" /></td>
        </tr>
    </tbody>
    <tfoot id="infoFoot">
        <tr><td colspan="4" id="infosave">
               
            </td> </tr>
    </tfoot>
</table>

<span id="btnLoggin" type="submit" class="btn btn-primary" data-url="@Url.Action("OTLista", "Index")">
    <i class="fa fa-save fa-1x"></i>
    Guardar Mis Avances
</span>

MaquetacionHTML/Views/Index/OTLista.cshtml
<div class="OTLista">
    <div class="col-md-12 col-sm-12" >
        <label for="txtUser" class="lblIcons">
            <i class="fa fa-user-circle fa-2x"></i>
        </label>
        <label class="lblText lblTxtImg">Bienvenido(a) MARIA ELIZABETH ESCOBEDO SEGURA </label>
    </div>
    <div id="dvMnuPrincipal" class="col-md-12 col-sm-12">
        <h3>¿Que deseas hacer?</h3>
        <ul id="allMenu" class="list-mnu">
            <li class="lst-item-menu" id="liDwnOt"><i class="fa fa-globe fa-2x mnuOp" data-url="" data-fn="fnSimulaSincronizacion"></i> <label id="lblTargetMnu1" data-url="@Url.Action("FakeDescarga", "Index")" class="lblText lblTxtImg">Sincronizar mis ordenes.</label></li>
            <li class="lst-item-menu"><i class="fa fa-file-o fa-2x mnuOp" data-url="@Url.Action("MisOrdenes", "Index")"></i> <label class="lblText lblTxtImg">Mis ordenes de trabajo.</label></li>
            @*<li class="lst-item-menu"><i class="fa fa-industry fa-2x mnuOp" data-url="@Url.Action("IniciarOrden", "Index")"></i> <label class="lblText lblTxtImg">Guardar Avance Orden de trabajo.</label></li>*@
            <li class="lst-item-menu"><i class="fa fa-sign-out fa-2x mnuOp" data-url="" data-fn="fnSalir"></i> <label class="lblText lblTxtImg">Salir.</label></li>
        </ul>
    </div>
    <div id="dvMnuPrincipalResult" class="col-md-12 col-sm-12">
    </div>
</div>

MaquetacionHTML/Views/Index/_InsumosByOt.cshtml
<table class="table table-condensed table-bordered">
    <thead class="grid-Head-Detalle navbar-default">
        <tr>
            <th>
                <div><label for="Codigo">Código</label></div>
            </th>
            <th>
                <div><label for="Serie">Serie</label></div>
            </th>
            <th>
                <div><label for="Descripcion">Descripción</label></div>
            </th>
            <th>
                <div><label for="Descripcion">Cantidad</label></div>
            </th>
        </tr>
    </thead>
    <tbody style="font-size:95%;text-align:left!important;">
        <tr class="ui-rw-cat">
            <td data-property="Codigo" data-property-value="1.02 TRA_T_C">
                <div>1.02 TRA_T_C</div>
            </td>
            <td data-property="Serie" data-property-value="1.02 TRA_T">
                <div>1.02 TRA_T</div>
            </td>
            <td data-property="Descripcion" data-property-value="Transcisión de Ducto Conduit a Ducto Plástico en Falso Plafón.">
                <div>Transcisión de Ducto Conduit a Ducto Plástico en Falso Plafón.</div>
            </td>

            <td data-property="Estatus" data-property-value="True">
                <span> 23</span>
            </td>
        </tr>
        <tr class="ui-rw-cat" data-property="IdInsumo" data-property-value="6">

            <td data-property="Codigo" data-property-value="101 FLETE">
                <div>101 FLETE</div>
            </td>
            <td data-property="Serie" data-property-value="101 FLETE">
                <div>101 FLETE</div>
            </td>
            <td data-property="Descripcion" data-property-value="Flete para envio o traslado de Materiales">
                <div>Flete para envio o traslado de Materiales</div>
            </td>
            <td data-property="Estatus" data-property-value="True">
                <span>22</span>
            </td>
        </tr>       
    </tbody>
</table>

MaquetacionHTML/Views/Shared/Modal.cshtml
<!-- Modal -->
<div id="dvModalMessageGlobal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header ModalTitle" style="color:#fff!important;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title " id="myModalLabel"></h4>
            </div>
            <div class="modal-body">
                <div id="pModalBodyGlobal">
                </div>
            </div>
            <div id="pModalFooterGlobal" class="modal-footer">
                <button id="btnModalAccept" type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>

MaquetacionHTML/Views/Shared/_Back.cshtml
<div class="list-mnu " id="dvbacktomenu"><i class="fa fa-arrow-left fa-2x" aria-hidden="true"><label class="lblText lblTxtImg">Atras</label></i></div>

MaquetacionHTML/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head id="headMainIcap">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Icap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Icap/Sistema/Base")
    @Scripts.Render("~/Icap/Sistema")
    @RenderSection("Scripts", false)
    <style>        
    .divtop 
    {
        width:100vw;height:50px;color:#fff;
        background-color:#286090       
    }
        .OTLista {
            color:#fff;
        }
        .list-mnu 
        {
            background-color:#286090;
        }
        .list-mnu-wait
        {
            background-color:#f8ac0e;
        }
        .lst-item-menu 
        {
            text-decoration:none;
            display:block;
            width:100%;
            height:40px;
          /*  background: rgba(255,255,255,0.5);*/
            color:#fff;
            cursor:pointer;            
        }
    </style>
    <script>
        function ini()
        {
            var top = document.getElementById('dvTop');
            top.ICAPM = new ICAPM();
            top.ICAPM.Loggin();
        }
        window.onload = ini;
    </script>
</head>
<body style="background-color:#17202A;">
    <div  id ="dvTop" class="divtop">
        <span style="margin-left:40%;font-size:300%"> ICAP </span>
    </div>
    @RenderBody()
</body>
</html>